import { AVAILABLE_PLATES } from '../constants/gym'
import type { BarWeight, Percentage, PercentageResult, PlateDistribution, RoundingMethod } from './calculator.types'
const CENTI_KILOS = 100
const LOAD_INCREMENT = 250
export const parseKilograms = (value: string): number | null => { const normalized = value.trim().replace(',', '.'); if (normalized === '' || !/^\d+(?:\.\d{0,2})?$/.test(normalized)) return null; const kilograms = Number(normalized); return Number.isFinite(kilograms) ? Math.round(kilograms * CENTI_KILOS) : null }
export const calculateTheoreticalWeight = (rp: number, percentage: Percentage): number => Math.round((rp * percentage) / 100)
export const findLoadableWeight = (theoreticalWeight: number, barWeight: BarWeight, method: RoundingMethod): number => { const barInCentiKilos = barWeight * CENTI_KILOS; if (theoreticalWeight <= barInCentiKilos) return barInCentiKilos; const difference = theoreticalWeight - barInCentiKilos; const lower = barInCentiKilos + Math.floor(difference / LOAD_INCREMENT) * LOAD_INCREMENT; if (method === 'down' || lower === theoreticalWeight) return lower; const upper = lower + LOAD_INCREMENT; return theoreticalWeight - lower <= upper - theoreticalWeight ? lower : upper }
export const calculatePlatesPerSide = (loadableWeight: number, barWeight: BarWeight): PlateDistribution[] => { let remaining = (loadableWeight - barWeight * CENTI_KILOS) / 2; return AVAILABLE_PLATES.flatMap((plateWeight) => { const plateInCentiKilos = plateWeight * CENTI_KILOS; const count = Math.floor(remaining / plateInCentiKilos); remaining -= count * plateInCentiKilos; return count > 0 ? [{ plateWeight, count }] : [] }) }
export const calculatePercentageResult = (rp: number, percentage: Percentage, barWeight: BarWeight, method: RoundingMethod): PercentageResult => { const theoreticalWeight = calculateTheoreticalWeight(rp, percentage); const loadableWeight = findLoadableWeight(theoreticalWeight, barWeight, method); return { percentage, theoreticalWeight, loadableWeight, difference: loadableWeight - theoreticalWeight, platesPerSide: calculatePlatesPerSide(loadableWeight, barWeight) } }
