import { NavLink } from 'react-router-dom'
interface MobileGlassNavigationProps { onAddPersonalRecord: () => void }
function DashboardIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><rect height="7" rx="1" width="7" x="3" y="3"/><rect height="7" rx="1" width="7" x="14" y="3"/><rect height="7" rx="1" width="7" x="3" y="14"/><path d="M14 18h7M17.5 14.5v7"/></svg> }
function ProgressIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 19 9 13l4 3 7-10"/><circle cx="4" cy="19" r="1"/><circle cx="9" cy="13" r="1"/><circle cx="13" cy="16" r="1"/><circle cx="20" cy="6" r="1"/></svg> }
function CalculatorIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><rect height="19" rx="2" width="14" x="5" y="2"/><path d="M8 6h8M8 11h2m4 0h2m-8 4h2m4 0h2"/></svg> }
function HistoryIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7 3h10v18H7zM10 8h4M10 12h4M10 16h2"/></svg> }
function PlusIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg> }
function AccountIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg> }
export function MobileGlassNavigation({ onAddPersonalRecord }: MobileGlassNavigationProps) { return <nav aria-label="Navegación principal" className="mobile-glass-navigation"><NavLink aria-label="Inicio" className={({ isActive }) => `mobile-glass-navigation__item${isActive ? ' is-active' : ''}`} to="/dashboard"><DashboardIcon/><span>Inicio</span></NavLink><NavLink aria-label="Progreso" className={({ isActive }) => `mobile-glass-navigation__item${isActive ? ' is-active' : ''}`} to="/progreso"><ProgressIcon/><span>Progreso</span></NavLink><NavLink aria-label="Calcular" className={({ isActive }) => `mobile-glass-navigation__item${isActive ? ' is-active' : ''}`} to="/calculator"><CalculatorIcon/><span>Calcular</span></NavLink><NavLink aria-label="Historial" className={({ isActive }) => `mobile-glass-navigation__item${isActive ? ' is-active' : ''}`} to="/history"><HistoryIcon/><span>Historial</span></NavLink><button aria-label="Agregar PR" className="mobile-glass-navigation__item mobile-glass-navigation__add" onClick={onAddPersonalRecord} type="button"><PlusIcon/><span>Agregar</span></button><NavLink aria-label="Cuenta" className={({ isActive }) => `mobile-glass-navigation__item${isActive ? ' is-active' : ''}`} to="/account"><AccountIcon/><span>Cuenta</span></NavLink></nav> }
