import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/useAuth'
import { AppHeader } from '../components/layout/AppHeader'
import { PrivateNavigation } from '../components/layout/PrivateNavigation'
import { supabase } from '../lib/supabase'
import type { BarWeight, RoundingMethod } from '../domain/calculator.types'

interface ProfileSummary { display_name: string | null; avatar_url: string | null; default_bar_weight: BarWeight; rounding_mode: RoundingMethod }

export function AccountPage() {
  const { signOut, user } = useAuth(); const navigate = useNavigate()
  const [profile, setProfile] = useState<ProfileSummary | null>(null); const [plateCount, setPlateCount] = useState<number | null>(null)
  const [barWeight, setBarWeight] = useState<BarWeight>(20); const [roundingMode, setRoundingMode] = useState<RoundingMethod>('nearest')
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [signingOut, setSigningOut] = useState(false); const [message, setMessage] = useState<string | null>(null)
  useEffect(() => { if (!user) return; let active = true; void Promise.all([supabase.from('profiles').select('display_name, avatar_url, default_bar_weight, rounding_mode').eq('id', user.id).maybeSingle(), supabase.from('user_plates').select('id', { count: 'exact', head: true }).eq('user_id', user.id)]).then(([profileResponse, platesResponse]) => { if (!active) return; if (profileResponse.error || platesResponse.error) setMessage('No se pudieron cargar tus preferencias.'); else { const nextBarWeight: BarWeight = profileResponse.data?.default_bar_weight === 15 ? 15 : 20; const nextRoundingMode: RoundingMethod = profileResponse.data?.rounding_mode === 'down' ? 'down' : 'nearest'; setProfile(profileResponse.data ? { ...profileResponse.data, default_bar_weight: nextBarWeight, rounding_mode: nextRoundingMode } : null); setBarWeight(nextBarWeight); setRoundingMode(nextRoundingMode); setPlateCount(platesResponse.count ?? 0) } }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [user])
  const accountName = profile?.display_name || user?.email || 'Usuario'
  const savePreferences = async () => { if (!user) return; setSaving(true); setMessage(null); const { error } = await supabase.from('profiles').update({ default_bar_weight: barWeight, rounding_mode: roundingMode }).eq('id', user.id); if (error) setMessage('No se pudieron guardar tus preferencias.'); else setProfile((current) => current ? { ...current, default_bar_weight: barWeight, rounding_mode: roundingMode } : current); setSaving(false) }
  const handleSignOut = async () => { setSigningOut(true); const error = await signOut(); if (error) { setMessage('No se pudo cerrar la sesión.'); setSigningOut(false); return }; navigate('/', { replace: true }) }
  return <main className="app-shell app-shell--private account-page"><AppHeader/><PrivateNavigation/><section className="account-page__hero"><div className="private-identity">{profile?.avatar_url ? <img alt="" className="account-avatar account-page__avatar" src={profile.avatar_url}/> : <span aria-hidden="true" className="account-avatar account-avatar-fallback account-page__avatar">{accountName.slice(0, 1).toUpperCase()}</span>}<div><p className="eyebrow">MI CUENTA</p><h1 className={accountName.includes('@') ? 'account-email-title' : ''}>{accountName}</h1></div></div></section>{loading ? <p className="account-status">Cargando preferencias…</p> : <section aria-label="Preferencias de cuenta" className="account-page__details account-preferences"><h2>Preferencias</h2><div className="account-preferences__controls"><fieldset><legend>Barra predeterminada</legend><div className="segmented">{([20, 15] as const).map((weight) => <button aria-pressed={barWeight === weight} className={`choice-button${barWeight === weight ? ' is-active' : ''}`} key={weight} onClick={() => setBarWeight(weight)} type="button">{weight} kg</button>)}</div></fieldset><fieldset><legend>Modo de ajuste</legend><div className="segmented"><button aria-pressed={roundingMode === 'nearest'} className={`choice-button${roundingMode === 'nearest' ? ' is-active' : ''}`} onClick={() => setRoundingMode('nearest')} type="button">Cercano</button><button aria-pressed={roundingMode === 'down'} className={`choice-button${roundingMode === 'down' ? ' is-active' : ''}`} onClick={() => setRoundingMode('down')} type="button">Abajo</button></div></fieldset></div><button className="account-preferences__save" disabled={saving} onClick={() => void savePreferences()} type="button">{saving ? 'Guardando…' : 'Guardar preferencias'}</button><div className="account-preferences__plates"><span>Discos configurados</span><strong>{plateCount ?? '—'}</strong><small>Se usan automáticamente para armar los pesos.</small></div></section>}{message && <p className="auth-message is-error" role="alert">{message}</p>}<div className="account-page__actions"><button className="account-page__signout" disabled={signingOut} onClick={() => void handleSignOut()} type="button">{signingOut ? 'Cerrando sesión…' : 'Cerrar sesión'}</button><Link className="account-page__home" to="/">Volver al inicio</Link></div></main>
}
